# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box      = "centos/7"
  config.vm.hostname = "puppet-book.local"

  config.vm.define :app do |app_config|
    app_config.vm.hostname = "app.puppet-book.local"
    app_config.vm.network :private_network, ip: "192.168.1.100"
    app_config.vm.synced_folder "./", "/vagrant", type: "virtualbox"
  end

  config.vm.define :log do |log_config|
    log_config.vm.hostname = "log.puppet-book.local"
    log_config.vm.network :private_network, ip: "192.168.1.101"
    log_config.vm.network :forwarded_port, guest: 24224, host: 24224
    log_config.vm.synced_folder "./", "/vagrant", type: "virtualbox"
  end
end
